Repository SWH-syncrow/syncrew-backend, pull requests merged in 2023-08, with the labels that each got.

#13 feat: 친구 신청글 수정
  src/main/java/com/example/syncrowbackend/friend/controller/PostController.java
  src/main/java/com/example/syncrowbackend/friend/dto/GetUserResponseDto.java
  src/main/java/com/example/syncrowbackend/friend/dto/PostDto.java
  src/main/java/com/example/syncrowbackend/friend/dto/WriterDto.java
  src/main/java/com/example/syncrowbackend/friend/entity/FriendRequest.java
  src/main/java/com/example/syncrowbackend/friend/repository/FriendRequestRepository.java
  src/main/java/com/example/syncrowbackend/friend/service/PostService.java
  src/main/java/com/example/syncrowbackend/friend/service/PostServiceImpl.java
Labels: enhancement

#19 refactor: 서비스 리팩토링 및 패키지 구조 변경
  src/main/java/com/example/syncrowbackend/auth/controller/AuthController.java
  src/main/java/com/example/syncrowbackend/auth/dto/KakaoUserDto.java
  src/main/java/com/example/syncrowbackend/auth/dto/LoginRequestDto.java
  src/main/java/com/example/syncrowbackend/auth/dto/LoginResponseDto.java
  src/main/java/com/example/syncrowbackend/auth/dto/ReissueRequestDto.java
  src/main/java/com/example/syncrowbackend/auth/dto/UserResponseDto.java
  src/main/java/com/example/syncrowbackend/auth/entity/User.java
  src/main/java/com/example/syncrowbackend/auth/entity/UserRole.java
  src/main/java/com/example/syncrowbackend/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/syncrowbackend/auth/jwt/TokenProvider.java
  src/main/java/com/example/syncrowbackend/auth/jwt/TokenResponseDto.java
  src/main/java/com/example/syncrowbackend/auth/repository/UserRepository.java
  src/main/java/com/example/syncrowbackend/auth/security/SecurityConfig.java
  src/main/java/com/example/syncrowbackend/auth/security/UserDetailsImpl.java
  src/main/java/com/example/syncrowbackend/auth/security/UserDetailsServiceImpl.java
  src/main/java/com/example/syncrowbackend/auth/service/AuthService.java
  src/main/java/com/example/syncrowbackend/auth/service/AuthServiceImpl.java
  src/main/java/com/example/syncrowbackend/common/exception/ErrorCode.java
  src/main/java/com/example/syncrowbackend/friend/controller/FriendController.java
  src/main/java/com/example/syncrowbackend/friend/controller/GroupController.java
  src/main/java/com/example/syncrowbackend/friend/controller/NotificationController.java
  src/main/java/com/example/syncrowbackend/friend/controller/PostController.java
  src/main/java/com/example/syncrowbackend/friend/dto/WriterDto.java
  src/main/java/com/example/syncrowbackend/friend/entity/FriendRequest.java
  src/main/java/com/example/syncrowbackend/friend/entity/Notification.java
  src/main/java/com/example/syncrowbackend/friend/entity/Post.java
  src/main/java/com/example/syncrowbackend/friend/entity/UserGroup.java
  src/main/java/com/example/syncrowbackend/friend/repository/FriendRequestRepository.java
  src/main/java/com/example/syncrowbackend/friend/repository/GroupRepository.java
  src/main/java/com/example/syncrowbackend/friend/repository/NotificationRepository.java
  src/main/java/com/example/syncrowbackend/friend/repository/UserGroupRepository.java
  src/main/java/com/example/syncrowbackend/friend/service/FriendService.java
  src/main/java/com/example/syncrowbackend/friend/service/FriendServiceImpl.java
  src/main/java/com/example/syncrowbackend/friend/service/GroupService.java
  src/main/java/com/example/syncrowbackend/friend/service/GroupServiceImpl.java
  src/main/java/com/example/syncrowbackend/friend/service/NotificationService.java
  src/main/java/com/example/syncrowbackend/friend/service/NotificationServiceImpl.java
  src/main/java/com/example/syncrowbackend/friend/service/PostService.java
  src/main/java/com/example/syncrowbackend/friend/service/PostServiceImpl.java
  src/main/java/com/example/syncrowbackend/user/service/AuthService.java
Labels: refactor

#22 feat: 신청글, 신청완료 조회 수정
  src/main/java/com/example/syncrowbackend/friend/controller/GroupController.java
  src/main/java/com/example/syncrowbackend/friend/controller/PostController.java
  src/main/java/com/example/syncrowbackend/friend/repository/FriendRequestRepository.java
  src/main/java/com/example/syncrowbackend/friend/repository/GroupRepository.java
  src/main/java/com/example/syncrowbackend/friend/service/FriendServiceImpl.java
  src/main/java/com/example/syncrowbackend/friend/service/GroupService.java
  src/main/java/com/example/syncrowbackend/friend/service/GroupServiceImpl.java
  src/main/java/com/example/syncrowbackend/friend/service/PostService.java
  src/main/java/com/example/syncrowbackend/friend/service/PostServiceImpl.java
Labels: enhancement

#24 feat: 요구사항 반영 및 전체 코드 리팩토링
  src/main/java/com/example/syncrowbackend/auth/controller/AuthController.java
  src/main/java/com/example/syncrowbackend/auth/dto/LoginResponseDto.java
  src/main/java/com/example/syncrowbackend/auth/dto/ReissueRequestDto.java
  src/main/java/com/example/syncrowbackend/auth/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/syncrowbackend/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/syncrowbackend/auth/jwt/TokenDto.java
  src/main/java/com/example/syncrowbackend/auth/jwt/TokenProvider.java
  src/main/java/com/example/syncrowbackend/auth/security/SecurityConfig.java
  src/main/java/com/example/syncrowbackend/auth/service/AuthService.java
  src/main/java/com/example/syncrowbackend/auth/service/AuthServiceImpl.java
  src/main/java/com/example/syncrowbackend/auth/service/RedisTokenService.java
  src/main/java/com/example/syncrowbackend/common/config/WebConfig.java
  src/main/java/com/example/syncrowbackend/common/exception/ErrorCode.java
  src/main/java/com/example/syncrowbackend/common/redis/RedisConfig.java
  src/main/java/com/example/syncrowbackend/common/redis/RedisUtil.java
  src/main/java/com/example/syncrowbackend/friend/controller/FriendController.java
  src/main/java/com/example/syncrowbackend/friend/controller/NotificationController.java
  src/main/java/com/example/syncrowbackend/friend/dto/FriendDto.java
  src/main/java/com/example/syncrowbackend/friend/dto/FriendReactionDto.java
  src/main/java/com/example/syncrowbackend/friend/dto/NotificationDto.java
  src/main/java/com/example/syncrowbackend/friend/enums/FriendReaction.java
  src/main/java/com/example/syncrowbackend/friend/service/FriendService.java
  src/main/java/com/example/syncrowbackend/friend/service/FriendServiceImpl.java
  src/main/java/com/example/syncrowbackend/friend/service/NotificationService.java
  src/main/java/com/example/syncrowbackend/friend/service/NotificationServiceImpl.java
  src/main/java/com/example/syncrowbackend/friend/util/StringToEnumConverter.java
Labels: enhancement

#27 docs: 리드미 구체화
  README.md
Labels: documentation
